import { Drug } from './types';

export const INITIAL_DRUG_MASTER_LIST: Drug[] = [];

export const INITIAL_DIAGNOSIS_LIST: string[] = [
  'Alopecia areata (rụng tóc tự miễn)',
  'Bạch biến (Vitiligo)',
  'Ban xuất huyết (Purpura)',
  'Carcinoma tế bào vảy (Squamous cell carcinoma)',
  'Carcinoma tế bào đáy (Basal cell carcinoma)',
  'Chốc lở (Impetigo)',
  'Dermatomyositis',
  'Dị dạng mạch máu bẩm sinh (Hemangioma, Port-wine stain)',
  'HPV – mụn cóc (Warts)',
  'Hidradenitis suppurativa',
  'Hồng ban (Erythema)',
  'Keratosis pilaris (mụn thịt)',
  'Lichen planus',
  'Lupus ban đỏ (Systemic / Cutaneous lupus erythematosus)',
  'Melanoma',
  'Molluscum contagiosum',
  'Mụn nang / mụn viêm (Nodulocystic acne)',
  'Mụn rộp sinh dục (Herpes simplex)',
  'Mụn trứng cá (Acne vulgaris)',
  'Mụn đầu đen / mụn đầu trắng (Comedonal acne)',
  'Mụn đỏ quanh miệng (Perioral dermatitis)',
  'Nhiễm trùng do liên cầu (Streptococcal skin infection)',
  'Nhiễm trùng do tụ cầu (Staphylococcal skin infection)',
  'Nám (Melasma)',
  'Nấm candida (Candidiasis)',
  'Nấm bẹn (Tinea cruris)',
  'Nấm móng (Onychomycosis)',
  'Nấm thân (Tinea corporis)',
  'Nấm da đầu (Tinea capitis)',
  'Nấm bàn chân (Tinea pedis)',
  'Pemphigoid',
  'Pemphigus vulgaris',
  'Pruritus (ngứa da không đặc hiệu)',
  'Rosacea',
  'Rubella',
  'Sởi (Measles / Rubeola)',
  'Thủy đậu (Varicella)',
  'Tăng sắc tố sau viêm (Post-inflammatory hyperpigmentation)',
  'Tàn nhang (Freckles / Ephelides)',
  'U mỡ (Lipoma)',
  'U tuyến bã (Sebaceous cyst)',
  'U xơ dưới da (Dermatofibroma)',
  'Vảy nến (Psoriasis)',
  'Viêm da cơ địa (Atopic dermatitis)',
  'Viêm da mụn nước (Dyshidrotic eczema)',
  'Viêm da nặng do ánh sáng (Photodermatitis)',
  'Viêm da tiết bã nhờn (Seborrheic dermatitis)',
  'Viêm da tiếp xúc dị ứng',
  'Viêm da tiếp xúc kích thích',
  'Viêm mô tế bào (Cellulitis)',
  'Viêm nang lông (Folliculitis)',
  'Zona (Herpes zoster)'
];
